### ISSUE TITLE
is it possible to set link, input and output colors based on data type?

### ISSUE THREAD

**Issue by RallyTronics** [Siviuze/Piper#3]
thanks!

**Comment by leducp** [comment]
Well, that's currently not possible, but I plan a rework of the node style and it seems a nice moment to integrate this. 
I can add a file that defines a default color and specific color per type.

**Comment by RallyTronics** [comment]
That sounds great, thanks.

**Comment by leducp** [comment]
Preliminary work is available in the branch theme_manager. Feel free to try it and let me know if this suits your use case (work in progress - issue reopened).

**Comment by leducp** [comment]
A first version of theme manager is available in master.
